# Site settings
# These are used to personalize your new site.
title: Matthew T. Weigel # your name here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer Science (class of 2023)
  <br /><br />
  <a href="/pdf/Matthew-Weigel-resume.pdf">View My Resume</a>
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/stu/users/25817525">View My Handshake Profile</a>
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/stu/users/25817525">View My LinkedIn Profile</a>
repository: "mtweigel/mtweigel.github.io"
github_username:  mtweigel # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

